variable "name" {}
variable "ports" {}
variable "ip_address" {}
variable "node_port" {}
variable "protocol" {}
variable "environment" {}
variable "visibility" {}
variable "aws_cert_arn" {}
variable "root_domain" {}
variable "uuid" {}
variable "is_tcp_listener" {}
variable "loadbalancer_idle_timeout" {}